name: CI-CD-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construir y ejecutar pruebas
        run: mvn clean verify --batch-mode

  sast-semgrep:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1

  dependency-check:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@v3.4.0
        with:
          project: "TiendaRopa"
          path: "."
          format: "HTML"
          out: "reports"

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

  secrets-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar Gitleaks (secrets scanning)
        uses: gitleaks/gitleaks-action@v2

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/tienda-ropa:${{ github.sha }} .

      - name: Push imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/tienda-ropa:${{ github.sha }}

  trivy-scan:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Escanear imagen con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/tienda-ropa:${{ github.sha }}
          format: table
          exit-code: 0

