name: DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  gitleaks:
    name: Secret Scanning - Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --verbose --redact

  snyk:
    name: Dependency Scanning - Snyk
    runs-on: ubuntu-latest
    needs: gitleaks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dar permisos a Maven Wrapper
        run: chmod +x ./tyvs-tienda-ropa/mvnw

      - name: Run Snyk Test
        working-directory: ./tyvs-tienda-ropa
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          ./mvnw dependency:tree -DoutputType=dot --batch-mode --non-recursive
          npx snyk test --severity-threshold=medium --all-sub-projects

  sonar:
    name: SAST - SonarQube Scan
    runs-on: ubuntu-latest
    needs: snyk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project (required for Sonar)
        working-directory: ./tyvs-tienda-ropa
        run: mvn -B clean package -DskipTests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./tyvs-tienda-ropa

  trivy:
    name: Container Scan - Trivy
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t tyvs-tienda-ropa:latest ./tyvs-tienda-ropa

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tyvs-tienda-ropa:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
